Supernova-teambits/edspresso-supernova

app/src/components/Card/CreateLessonCard.jsx
app/src/components/LessonSteps/LessonSteps.jsx
app/src/components/MentorVerification/MentorVerification.jsx
app/src/components/RecipeDetails.jsx
app/src/components/RecipeExecution/StepsMedia.jsx
app/src/pages/ProgressUpdate.jsx

[Desc]
- Add MentorVerification component
- Disable "Start quiz" button if completed_time is 0, and cancel disable completed_time is more than 1
- change button label and appear message depends on test_result
- Change style on breadcrumb depends on the progress
[To do]
- Pull "Chemex" progress data

Sup 173 menter verification

---

app/public/index.html
app/public/manifest.json
app/src/components/Card/CreateLessonCard.jsx
app/src/components/Card/ShortcutCard.jsx
app/src/components/SideBar.jsx
app/src/pages/LogIn.jsx
app/src/pages/dashboard/Dashboard.jsx
app/src/pages/dashboard/ShortcutContainer.jsx
app/src/recoil/selectors/filteredProgressState.js

bug fix to get ready to deploy

SUP-164 bug fix

---

app/src/components/MentorVerification/MentorVerification.jsx

add condition

---

app/src/utils/Constants.js
server/app.js
server/views/index.ejs

Change backend URL
- Backend hosting server change. (aws EC2 -> Railway)
- BASE_URL is changed.
- Server info updated. ( Endpoint link )

SUP-186 <Change backend URL>

---

app/src/components/Buttons/CloseButton.jsx
app/src/components/Buttons/Pagination.jsx
app/src/pages/QuizPage.jsx
app/src/pages/ResultPage.jsx

- Update closebutton color
- Update Pagination to disable "Back" button on first page
- Update QuizPage to match mockup
- Update Result mobile to have pagination for answers

Sup 188 add report pagination for mobile

---

app/src/components/Buttons/Button.jsx
app/src/components/RecipeDetails.jsx
app/src/pages/ProgressUpdate.jsx

[Desc]
- Due to changes in components
- Breadcrumbs -> Button

SUP-182 change button component

---

app/src/pages/LogIn.jsx

Fixed unused warning
- Fixed build waring  to display normally in Netlipy.

SUP-183 <Fixed unused warning>

---

app/src/App.scss
app/src/assets/images.js
app/src/components/Buttons/Button.jsx
app/src/components/Buttons/Button.scss
app/src/components/Card/DetailsCard.jsx
app/src/components/Card/DetailsCard.scss
app/src/components/Card/LessonCard.jsx
app/src/components/Card/LessonCard.scss
app/src/components/CardCollection/CardCollection.jsx
app/src/components/CardCollection/CardCollection.scss
app/src/components/LessonSteps/LessonSteps.jsx
app/src/components/MentorVerification/MentorVerification.jsx
app/src/components/MentorVerification/MentorVerification.scss
app/src/components/RecipeDetails.jsx
app/src/components/RecipeDetails.scss
app/src/components/SearchBar/SearchBar.jsx
app/src/pages/LogIn.jsx
app/src/pages/MyTraining.jsx
app/src/pages/MyTraining.scss
app/src/pages/dummy-lesson.js

[Desc]
-Apply styles to My Learning, Recipe Details 
[Todo]
-Apply styles to Progress Update, Setp-by-Step

Sup 182 apply css trainee side no quiz

---

app/src/components/Card/AdminDashboard.scss
app/src/components/Chart/DonutChart.jsx
app/src/pages/dashboard/ProgressStatusLabel.jsx
app/src/pages/dashboard/TraineeLearningProcess.jsx
app/src/utils/Constants.js

CSS for Analytics - Learning process

SUP-183 <CSS for Analytics - Learning process>

---

app/src/components/Buttons/CloseButton.jsx
app/src/components/Buttons/Pagination.jsx
app/src/pages/QuizPage.jsx
app/src/pages/QuizPage.scss
app/src/routes/routes.js
app/src/sass/_typography.scss

- Add styling to CloseButton
- Add styling to Pagination
- Add @mixin for mobile styling
- Add specific route for step/6 (QuizPage) to remove Nav bar
- Add styling for desktop/mobile

Sup 185 apply css

---

app/src/pages/LogIn.jsx
app/src/pages/dashboard/Dashboard.jsx

Fix issue didn't get data when refresh in Dashboard.
- Stored manager_code info in localhost storage.
- If manager_code info is "undefined", uses localhost info.

[Bug] Fix issue didn't get data when refresh.

---

server/controllers/progressController.js
server/models/Progress.js

[DESC]
- Add started_date field in Progress db.

[Backend] Add started_date field in Progress db

---

app/src/components/Chart/DonutChart.jsx
app/src/components/Chart/DonutChart.scss
app/src/pages/LogIn.jsx
app/src/pages/Login.scss
app/src/pages/dashboard/Analytics.jsx
app/src/pages/dashboard/Analytics.scss
app/src/pages/dashboard/TraineeProgressChart.jsx
app/src/pages/dashboard/TraineeProgressFilter.jsx
app/src/pages/dashboard/TraineeProgressStats.jsx
app/src/sass/_typography.scss
app/src/utils/ThemeUtil.js

[Desc]
Apply css lesson analytics

💄 <Sup 183> apply css login analytics

---

app/src/pages/LogIn.jsx
app/src/pages/Login.scss

Styling Login page
- Changed MUI Button component to button element bacause scss adaptation issue.
- Change TextField label ( name -< Username )

💄SUP-183 <CSS for Login page - 3>

---

app/src/pages/dashboard/Analytics.jsx
app/src/pages/dashboard/Analytics.scss
app/src/pages/dashboard/ProgressStatusLabel.jsx
app/src/pages/dashboard/TraineeLearningProcess.jsx

[Desc]
CSS for learning process page.

SUP-183 <CSS for learning process page >

---

app/src/components/Buttons/Pagination.jsx
app/src/pages/QuizPage.scss
app/src/pages/ResultPage.scss

- Add cursor point
- Add hover color
- Adjust positioning affected by global styling

Add pointer, hover, positioning

---

app/src/components/Card/ShortcutCard.jsx

[DESC]
Delete unused varable ( imageSrc )

[Hotfix] delete unused varable

---

app/src/components/Layout.jsx

change width value

---

app/src/components/MentorVerification/MentorVerification.jsx

[Desc]
- Remove Promise.All to follow React documentation

BUG-15 not reflecting test_result to component

---

app/src/components/LessonSteps/LessonSteps.jsx
app/src/components/MentorVerification/MentorVerification.jsx

[Desc]
- Apply axios on Step5 page to update completed_time (randomly generated number for now)
- set completed_time as second argument in useEffect on Step5 page to execute functions after rendering

BUG-15 Apply axios on Step5 page to update completed_time

---

app/src/pages/dashboard/TraineeLearningProcess.jsx
app/src/recoil/selectors/filteredProgressState.js
server/controllers/progressController.js
server/models/Progress.js

Display trainee's picture
- [Backend] Add trainee_photo field in Progress document.
- [Frontend] Display trainee's picture. ( If there is no picture url, display default image )

SUP-201 <Display trainee's picture>

---

app/src/pages/LogIn.jsx
app/src/pages/Login.scss
app/src/utils/Constants.js

[DESC]
- Apply Responsive to Login page

SUP-212 <Apply Responsive to Login page>

---

app/src/components/LessonSteps/LessonSteps.jsx

[Desc]
- original function generate could generate 999min. for one lesson, that doesn't make sense.
[Fix]
- Modify expected output between 1 and 100

Bug-32  Modify expected output value from 1-999 to 1-100

---

app/src/components/Chart/DonutChart.jsx
app/src/pages/dashboard/Analytics.scss
app/src/pages/dashboard/TraineeLearningProcess.jsx
app/src/pages/dashboard/TraineeProgressChart.jsx
app/src/pages/dashboard/TraineeProgressStats.jsx
app/src/utils/Constants.js

[DESC]
- Make Analytics page to responsive

SUP-216 <Make Analytics page to responsive>

---

app/src/components/Buttons/Button.jsx
app/src/components/Buttons/Button.scss
app/src/components/LessonSteps/LessonSteps.jsx
app/src/components/MentorVerification/MentorVerification.jsx
app/src/components/RecipeDetails.jsx

[Bug-14]
- Change progress on Recipe details page is not updated after user finishes lesson
[Bug-16]
- "Start Lesson" button is supposed to be changed to "Review Lesson" after user finishes the lesson
[Fix]
- Add function to update progress_status on Step 5
- Add function to check progress_status when user go back to Recipe Details page
- (Remove updating completed_time function to avoid confusion)
- Display either "Start Lesson" or "Review Lesson" depends on progress_status on Database

Bug-16  Button in Recipe Details page doesn't change

---

app/src/pages/ProgressUpdate.jsx
app/src/pages/ProgressUpdate.scss

[Desc]
- I mixed up progress update page and progress finish page, actually they are different.
- So need to make another component for progress finish page.

SUP-204 add component for displaying progress done

---

app/src/pages/LogIn.jsx
app/src/pages/Login.scss
app/src/utils/ThemeUtil.js

Update Login page
- Add loading process while check auth
- Login button disable when didn't input username

Update Login page

---

app/src/App.js
app/src/components/Layout.jsx
app/src/components/SideBar.jsx
app/src/index.js
app/src/pages/LogIn.jsx

Fix session persistence

---

app/src/components/Chart/DonutChart.jsx
app/src/pages/dashboard/Dashboard.jsx
app/src/pages/dashboard/ProgressStatusLabel.jsx
app/src/pages/dashboard/TraineeProgressChart.jsx

Apply css responsive to analytics
- Add margin to Dashboard.
- Some style change in mobile size.

📱Sup 216 <apply css responsive to analytics>

---

app/src/components/Buttons/CloseButton.jsx
app/src/pages/QuizPage.jsx
app/src/pages/QuizPage.scss
app/src/pages/ResultPage.jsx
app/src/pages/ResultPage.scss

- update close button font
- update radio button text align

fix button css

---

app/src/components/Chart/DonutChart.jsx

Deleted unused Component ( ResponsiveContainer )

Deleted unused Component

---

app/src/components/Buttons/Button.scss
app/src/components/Card/TipsCard.scss
app/src/components/Header/LessonHeader.scss
app/src/components/LessonSteps/LessonSteps.jsx
app/src/components/LessonSteps/LessonSteps.scss
app/src/components/MentorVerification/MentorVerification.scss
app/src/components/RecipeDetails.jsx
app/src/components/RecipeDetails.scss
app/src/components/RecipeExecution.scss
app/src/components/RecipeExecution/StepMedia.jsx
app/src/components/RecipeExecution/StepMedia.scss
app/src/components/RecipeExecution/StepProgress.jsx
app/src/components/RecipeExecution/StepProgress.scss
app/src/pages/MyTraining.scss
app/src/pages/ProgressUpdate.jsx
app/src/pages/ProgressUpdate.scss
app/src/pages/TrainingDetails.scss
app/src/pages/dummy-steps.js

[Desc]
- Apply CSS to MediaCarousel component
- Support Responsiveness
- Improve general spacing
- Wordings

Sup-210 apply css add color to media carousel buttons

---

app/src/pages/dummy-question.js

shorten quiz answer to fit screen

shorten quiz answer

---

app/src/assets/Icons.js
app/src/components/Card/DetailsCard.jsx
app/src/components/Card/DetailsCard.scss
app/src/components/Header/LessonHeader.scss
app/src/components/LessonSteps/LessonSteps.jsx
app/src/components/LessonSteps/LessonSteps.scss
app/src/components/MentorVerification/MentorVerification.jsx
app/src/components/RecipeDetails.jsx
app/src/components/RecipeDetails.scss
app/src/components/RecipeExecution.scss
app/src/components/RecipeExecution/StepMedia.scss
app/src/pages/TrainingDetails.scss
app/src/pages/dummy-steps.js

[Desc]
- Apply responsive design for ingredients list
- Adjust space and font for responsiveness
- Fix typo

Sup-215 apply css ingredients equipment list for mobile

---

app/src/assets/Icons.js
app/src/components/Header/LessonHeader.scss
app/src/components/MentorVerification/MentorVerification.scss
app/src/components/RecipeExecution.scss
app/src/components/RecipeExecution/StepMedia.jsx
app/src/components/RecipeExecution/StepMedia.scss
app/src/pages/ProgressUpdate.scss

[Desc]
- Apply responsiveness to Ratio Calculation

Sup-211 apply css ratio calculater component

---

app/src/components/Card/LessonCard.jsx
app/src/components/Card/LessonCard.scss
app/src/components/CardCollection/CardCollection.jsx
app/src/components/CardCollection/CardCollection.scss
app/src/components/RecipeDetails.scss
app/src/components/RecipeExecution/StepMedia.jsx
app/src/components/RecipeExecution/StepMedia.scss
app/src/components/SearchBar/SearchBar.jsx
app/src/pages/MyTraining.jsx
app/src/pages/MyTraining.scss
app/src/utils/ThemeUtil.js

[Desc]
- Fix bugs that elements are overlapping when screen size is small on MyLearning page

Sup-211 Fix bugs on MyLearning page

---

app/src/components/RecipeExecution/StepMedia.jsx

SUP-211 add onChange

---

app/src/components/Card/AdminDashboard.scss
app/src/components/Card/CreateLessonCard.jsx
app/src/components/Card/ShortcutCard.jsx
app/src/components/Sidebar.scss

Fix button arrow positioning, change the text in barista card in admin dashboard for mobile view

Fix button arrows

---

app/src/recoil/selectors/filteredProgressState.js

[DESC]
Apply sort in trainee progress

SUP-226 <Apply sort in trainee progress>

---

app/src/pages/LogIn.jsx

[DESC]
This code don't request to backend when username is empty.

don't query to backend when username is empty

---

app/src/pages/dashboard/Analytics.scss
app/src/pages/dashboard/TraineeLearningProcess.jsx
app/src/pages/dashboard/TraineeProgressChart.jsx

[DESC]
Show related text when no content in selected lesson & time in dashboard.

SUP-226 <Add text when no content>

---

app/src/components/Card/DetailsCard.jsx
app/src/components/Card/DetailsCard.scss
app/src/components/MentorVerification/MentorVerification.jsx
app/src/components/MentorVerification/MentorVerification.scss
app/src/pages/TrainingDetails.jsx

[DESC]
- Modify styling
- Remove sentence from mentor verification if user passed the test

Sup 224 apply css trainee side

---

app/src/pages/dashboard/TraineeLearningProcess.jsx

[Problem]
Wrong wording. ( https://supernova7.atlassian.net/browse/BUG-85 )
[Cause]
Set wrong wording.
[Fix]
Change word.

BUG-85 <Change wording>

---

app/src/components/Buttons/Button.scss

[Bug]
Button on header was not alined with other elements.
[Fix]
Set proper padding

Bug-60 my learnings navigation arrow should be aligned to chemex method

---

app/src/components/RecipeExecution/StepMedia.jsx
app/src/components/RecipeExecution/StepProgress.jsx
app/src/components/RecipeExecution/StepProgress.scss

[Bug]
Font style is not applied
[Fix]
Changed the way to apply

Bug 82  trainee mobile   lesson navigation menu  font style is not accurate

---

app/src/pages/dashboard/Dashboard.scss

[Problem]
Dashboard is not responsive properly
( https://supernova7.atlassian.net/browse/BUG-53 )
[Cause]
Didn't consider sidebar width 
[Fix]
Add margin for sidebar

BUG-53 <Make dashboard to responsive>

---

app/src/pages/ResultPage.scss

Bug 84 trainee mobile quiz results font style is not accurate

---

app/src/components/Select/FilterSelect.jsx
app/src/components/Select/FilterSelect.scss
app/src/pages/dashboard/Analytics.scss
app/src/pages/dashboard/TraineeProgressFilter.jsx
app/src/utils/Constants.js

[Problem]
Filter arrow icon is not one from Mockup.
( https://supernova7.atlassian.net/browse/BUG-72 )
[Cause]
Didn't adapt released arrow icon
[Fix]
Change icon to released arrow icon

BUG-72 <Change filter arrow icon>

---

app/src/pages/QuizPage.scss

Bug 83 trainee mobile quiz answer options font style is not accurate

---

app/src/pages/ResultPage.jsx

add condition to note message to disappear if passed test

Bug 71 result note message should disappear if passed the test

---

app/src/components/Buttons/Pagination.jsx
app/src/pages/QuizPage.scss

- remove padding for mobile
- adjust width for pagination

Change padding for mobile

---

app/src/components/Buttons/CloseButton.jsx
app/src/pages/QuizPage.jsx
app/src/pages/QuizPage.scss

- Change modal size, font, color
- Remove modal header

change modal size

---

app/src/pages/QuizPage.jsx

- calculate score and redirect to result page after timeout

Bug 40 the questionnaire keep still after timer is over

---

app/src/pages/dashboard/Analytics.scss
app/src/pages/dashboard/TraineeLearningProcess.jsx
app/src/pages/dashboard/TraineeProgressChart.jsx
app/src/pages/dashboard/TraineeProgressStats.jsx

[Problem]
Wrong border-radius on Dashboard screen
( https://supernova7.atlassian.net/browse/BUG-45 )
[Cause]
Use MUI original setting
[Fix]
Add border-radius and shadow property

BUG-45 <Update dashboard border-radius>

---

app/src/pages/ResultPage.jsx

Add text for incorrect option

---

app/src/components/RecipeExecution/StepMedia.jsx

[Cause]
- Input type was not set properly.
[Fix]
- set type="number" to accept only numeric input

Bug-81 Input validation problem

---

app/src/components/Layout.jsx
app/src/components/RecipeExecution.scss
app/src/pages/ProgressUpdate.jsx
app/src/pages/ProgressUpdate.scss

[Cause]
- didn't set flex-grow to the content in the middle
[Fix]
- set flex-grow to the content in the middle in Recipe execution and Progress update

BUG-38 The step navigation bar is moved from the bottom

---

app/src/components/RecipeDetails.jsx
app/src/components/RecipeDetails.scss

[Problem]
Wrong border-radius on Recipe Details page
( https://supernova7.atlassian.net/browse/BUG-79 )
[Cause]
Use MUI original setting
[Fix]
Add border-radius and set font family

Bug-79  Training  incorrect border radius in training requirements

---

app/src/pages/ProgressUpdate.jsx

[Problem]
Indicates wrong progress when user finish all steps on mobile
( https://supernova7.atlassian.net/browse/BUG-41 )
[Cause]
set wrong parameter
[Fix]
set proper parameter

BUG-41 Fix indicator mistakes

---

app/src/components/RecipeDetails.jsx

[Problem]
"Requirement" and "weight" are supposed to "Requirements" and "Weight"
( https://supernova7.atlassian.net/browse/BUG-56 )
[Cause]
Typo
[Fix]
Fix typo

BUG-56 Spelling error in Requirements component
